# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 767616afa34eaadc6a55f49aeef4f69743d9ebcef2d1117fc85202a6499393e803e374df74b6fde3b79d9a2020c6be89922443fff73cc859030c7e4810082015

test:
  secret_key_base: 914ec6b886ba104663702265fbf4bf365a4b3ffb37f02e9cbb6e0300f8f576cb8439acef5597cbfba601a4b15469590dd614df93637df03f2c1a60c2e455d577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
